spring:
  datasource:
    url: jdbc:postgresql://postgres_server:5432/postgres
    username: postgres
    password: admin123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true