#Spring configurations
spring:
  #Datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123456
    driver-class-name: org.postgresql.Driver
  #JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop      
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
  #Security configuration
#  security:
#    user:
#      name: usersecurity
#      password: passwordsecurity